# In The Name Of God
# ========================================
# [] File Name : Makefile
#
# [] Creation Date : 30-05-2016
#
# [] Created By : Parham Alvani (parham.alvani@gmail.com)
# =======================================

.PHONY: all
all: HW-6-sol

HW-6-sol: HW-6-sol.tex
	xelatex -shell-escape HW-6-sol.tex
