# In The Name Of God
# ========================================
# [] File Name : Makefile
#
# [] Creation Date : 05-03-2016
#
# [] Created By : Parham Alvani (parham.alvani@gmail.com)
# =======================================

.PHONY: all
all: HW-2-sol

HW-2-sol: HW-2-sol.tex
	xelatex -shell-escape HW-2-sol.tex
