# In The Name Of God
# ========================================
# [] File Name : Makefile
#
# [] Creation Date : 05-03-2016
#
# [] Created By : Parham Alvani (parham.alvani@gmail.com)
# =======================================

.PHONY: all
all: HW-1-sol

HW-1-sol: HW-1-sol.tex
	xelatex -shell-escape HW-1-sol.tex
